version: 2
updates:
  - package-ecosystem: "gomod"
    directories: 
      - "/installer"
      - "/agent-manager"
      - "/agent"
      - "/agent/self"
      - "/aws"
      - "/bitdefender"
      - "/correlation"
      - "/log-auth-proxy"
      - "/office365"
      - "/sophos"
      - "/soc-ai"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directories: 
      - "/backend"
      - "/user-auditor"
      - "/web-pdf"
    schedule:
      interval: "daily"
